//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_user
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string real_name { get; set; }
        public string mobile { get; set; }
        public bool isBase { get; set; }
        public int shop_id { get; set; }
    }
}
