//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVOURITE_SHOP
    {
        public int id { get; set; }
        public int uid { get; set; }
        public int shop_id { get; set; }
        public string goods_name { get; set; }
        public string recommend { get; set; }
        public int pic_id { get; set; }
    }
}
