//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ord
    {
        public int 订单标识 { get; set; }
        public string 订单号 { get; set; }
        public Nullable<System.DateTime> 下单时间 { get; set; }
        public Nullable<int> 交易类型 { get; set; }
        public int 商品标识 { get; set; }
        public string 商品名 { get; set; }
        public int 商品数量 { get; set; }
        public Nullable<decimal> 商品价格 { get; set; }
        public Nullable<int> 订单状态 { get; set; }
        public Nullable<int> 买方标识 { get; set; }
        public string 注册手机号 { get; set; }
        public Nullable<int> 支付渠道 { get; set; }
        public string 购买人姓名 { get; set; }
        public string 购买人电话 { get; set; }
        public string 购买人地址 { get; set; }
        public Nullable<System.DateTime> 发送时间 { get; set; }
    }
}
