//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderListView
    {
        public int order_id { get; set; }
        public string ordercode { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public int trans_type { get; set; }
        public string name { get; set; }
        public string supplier_code { get; set; }
        public Nullable<decimal> goods_supply_price { get; set; }
        public string goods_sku { get; set; }
        public int goods_count { get; set; }
        public Nullable<decimal> goods_price { get; set; }
        public string track_num { get; set; }
        public string message { get; set; }
        public int status { get; set; }
        public string username { get; set; }
        public string receive_name { get; set; }
        public string receive_mobile { get; set; }
        public string receive_address { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
    }
}
