//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_LIST_VIEW
    {
        public int id { get; set; }
        public string order_code { get; set; }
        public int uid { get; set; }
        public int shop_id { get; set; }
        public string shop_name { get; set; }
        public decimal money { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> postage { get; set; }
        public int status { get; set; }
        public Nullable<int> goods_count { get; set; }
        public Nullable<decimal> return_money { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public string track_com { get; set; }
        public string track_num { get; set; }
        public string receive_name { get; set; }
        public string receive_address { get; set; }
        public string receive_mobile { get; set; }
        public string check_code { get; set; }
    }
}
