//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_COUNT_INFO
    {
        public int order_id { get; set; }
        public Nullable<int> goods_count { get; set; }
        public int status { get; set; }
        public int buyer_id { get; set; }
        public int shop_id { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<System.DateTime> checktime { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> discount_income { get; set; }
        public Nullable<decimal> return_money { get; set; }
        public Nullable<decimal> postage { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> cash_pool_add { get; set; }
        public Nullable<decimal> buyer_recommend_award { get; set; }
        public Nullable<decimal> agent_award { get; set; }
    }
}
