//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMMEND_HOT_VIEW
    {
        public int id { get; set; }
        public decimal price { get; set; }
        public decimal local_price { get; set; }
        public string name { get; set; }
        public string propaganda { get; set; }
        public long pic_id { get; set; }
        public string return_money_rate { get; set; }
    }
}
