//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_order
    {
        public int id { get; set; }
        public string ordercode { get; set; }
        public int shop_id { get; set; }
        public int buyer_id { get; set; }
        public int trans_type { get; set; }
        public decimal money { get; set; }
        public int order_type { get; set; }
        public int status { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<System.DateTime> checktime { get; set; }
        public string shop_name { get; set; }
        public string shop_address { get; set; }
        public string area_code { get; set; }
        public string lng { get; set; }
        public string lat { get; set; }
        public string receive_name { get; set; }
        public string receive_address { get; set; }
        public string receive_mobile { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public string track_com { get; set; }
        public string track_num { get; set; }
        public string combine_code { get; set; }
        public bool is_paid { get; set; }
        public bool is_settled { get; set; }
        public string check_code { get; set; }
        public Nullable<int> warehouse_distribution { get; set; }
        public Nullable<int> user_coupons_id { get; set; }
        public Nullable<decimal> user_coupons_countmoney { get; set; }
        public string order_guid { get; set; }
        public Nullable<int> receive_id { get; set; }
    }
}
