//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_page_view_log
    {
        public int id { get; set; }
        public string route_info { get; set; }
        public System.DateTime addtime { get; set; }
        public int uid { get; set; }
    }
}
