//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_user_receive_info
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string receive_name { get; set; }
        public string receive_address { get; set; }
        public string receive_mobile { get; set; }
        public Nullable<System.DateTime> deletemark { get; set; }
        public string area_code { get; set; }
        public string zip_code { get; set; }
    }
}
