//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_shop_cate
    {
        public int id { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public int order_id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int type { get; set; }
        public int recommend_type { get; set; }
        public string redirect_type { get; set; }
        public string redirect_url { get; set; }
    }
}
