//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_user_bank_card
    {
        public int id { get; set; }
        public int uid { get; set; }
        public System.DateTime addtime { get; set; }
        public string bank_en { get; set; }
        public string card_no { get; set; }
        public string card_holder { get; set; }
        public Nullable<System.DateTime> deletemark { get; set; }
    }
}
