//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_goods_spec
    {
        public long id { get; set; }
        public int goods_id { get; set; }
        public string spec_class { get; set; }
        public string spec { get; set; }
        public decimal price_influence { get; set; }
        public int inv_count { get; set; }
        public int sell_count { get; set; }
        public int is_default { get; set; }
    }
}
