//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_shop_cart
    {
        public int id { get; set; }
        public int uid { get; set; }
        public int goods_id { get; set; }
        public int goods_count { get; set; }
        public bool isUsed { get; set; }
        public Nullable<System.DateTime> deletemark { get; set; }
    }
}
