//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_goods_attr_value_v2
    {
        public int id { get; set; }
        public Nullable<int> goods_id { get; set; }
        public string attr_color { get; set; }
        public string attr_size { get; set; }
        public string attr_spec { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> inv_count { get; set; }
        public Nullable<int> pic_id { get; set; }
    }
}
