//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_platform_data_record
    {
        public int id { get; set; }
        public Nullable<System.DateTime> stat_date { get; set; }
        public Nullable<decimal> total_user_money { get; set; }
        public Nullable<decimal> total_mall_consume_money { get; set; }
    }
}
