//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_goods_coupons
    {
        public int id { get; set; }
        public int goodsid { get; set; }
        public decimal money { get; set; }
        public decimal countmoney { get; set; }
        public int goldbean { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public string goodsname { get; set; }
        public System.DateTime addtime { get; set; }
        public Nullable<System.DateTime> deletemark { get; set; }
        public int goldcoin { get; set; }
        public decimal leastconsume { get; set; }
        public Nullable<int> displayindex { get; set; }
        public string type { get; set; }
        public Nullable<decimal> redpacket { get; set; }
    }
}
