//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_carousel_figure
    {
        public int id { get; set; }
        public int index_order { get; set; }
        public byte type { get; set; }
        public string des { get; set; }
        public int pic_id { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> deletemark { get; set; }
        public int direct_type { get; set; }
        public int cate_id { get; set; }
    }
}
