//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_order_info_goods
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int goods_id { get; set; }
        public int goods_count { get; set; }
        public int goods_type { get; set; }
        public Nullable<decimal> goods_price { get; set; }
        public string goods_name { get; set; }
        public Nullable<int> goods_pic_id { get; set; }
        public Nullable<decimal> cash_pay_rate { get; set; }
        public Nullable<decimal> beans_pay_rate { get; set; }
        public string msg_leave_word { get; set; }
        public string msg_phone { get; set; }
        public string msg_realname { get; set; }
        public string msg_idcardno { get; set; }
        public Nullable<decimal> postage { get; set; }
    }
}
