//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_type_translate
    {
        public int id { get; set; }
        public int typevalue { get; set; }
        public string des { get; set; }
        public string tablename { get; set; }
        public string typefield { get; set; }
        public bool is_used { get; set; }
    }
}
