//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_shop
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int addtime { get; set; }
        public string shop_name { get; set; }
        public string shop_address { get; set; }
        public string area_code { get; set; }
        public string license { get; set; }
        public string license_pic_id { get; set; }
        public string lng { get; set; }
        public string lat { get; set; }
        public string recommend { get; set; }
        public int fee_id { get; set; }
        public int pic_id { get; set; }
        public string shop_info { get; set; }
        public string shop_info_html { get; set; }
        public int sell_count { get; set; }
        public decimal sell_money { get; set; }
        public decimal evaluate_point { get; set; }
        public int evaluate_count { get; set; }
        public decimal evaluate_point_sum { get; set; }
        public int shop_type { get; set; }
        public decimal x_money { get; set; }
        public decimal x_money_last_day { get; set; }
    }
}
