//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_trans_record
    {
        public int id { get; set; }
        public string combine_order_code { get; set; }
        public int buyer_id { get; set; }
        public System.DateTime addtime { get; set; }
        public decimal money { get; set; }
        public decimal return_money { get; set; }
        public decimal postage { get; set; }
        public decimal fee { get; set; }
        public decimal cash_pool_add { get; set; }
        public decimal buyer_recommend_award { get; set; }
        public decimal agent_award { get; set; }
        public int trans_type { get; set; }
        public decimal discount { get; set; }
        public decimal discount_income { get; set; }
        public string remark { get; set; }
        public bool is_settled { get; set; }
    }
}
