//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_config
    {
        public long id { get; set; }
        public string Item { get; set; }
        public string Value { get; set; }
        public string Des { get; set; }
        public byte IsUsed { get; set; }
    }
}
