//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrl_sms
    {
        public int id { get; set; }
        public string mobile { get; set; }
        public string code { get; set; }
        public System.DateTime addtime { get; set; }
        public byte send_status { get; set; }
        public byte arrive_status { get; set; }
        public bool is_used { get; set; }
    }
}
