//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RRlModelContainer : DbContext
    {
        public RRlModelContainer()
            : base("name=RRlModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_module> admin_module { get; set; }
        public virtual DbSet<admin_role> admin_role { get; set; }
        public virtual DbSet<admin_role_power> admin_role_power { get; set; }
        public virtual DbSet<admin_user> admin_user { get; set; }
        public virtual DbSet<error_helper> error_helper { get; set; }
        public virtual DbSet<@event> @event { get; set; }
        public virtual DbSet<game_record_lose_0001_2018> game_record_lose_0001_2018 { get; set; }
        public virtual DbSet<game_record_lose_0002_2018> game_record_lose_0002_2018 { get; set; }
        public virtual DbSet<game_record_lose_0003_2018> game_record_lose_0003_2018 { get; set; }
        public virtual DbSet<game_record_lose_0004_2018> game_record_lose_0004_2018 { get; set; }
        public virtual DbSet<game_record_lose_0005_2018> game_record_lose_0005_2018 { get; set; }
        public virtual DbSet<game_record_win_0001_2018> game_record_win_0001_2018 { get; set; }
        public virtual DbSet<game_record_win_0002_2018> game_record_win_0002_2018 { get; set; }
        public virtual DbSet<game_record_win_0003_2018> game_record_win_0003_2018 { get; set; }
        public virtual DbSet<game_record_win_0004_2018> game_record_win_0004_2018 { get; set; }
        public virtual DbSet<game_record_win_0005_2018> game_record_win_0005_2018 { get; set; }
        public virtual DbSet<goods_temp> goods_temp { get; set; }
        public virtual DbSet<rrl_carousel_figure> rrl_carousel_figure { get; set; }
        public virtual DbSet<rrl_cash_apply> rrl_cash_apply { get; set; }
        public virtual DbSet<rrl_config> rrl_config { get; set; }
        public virtual DbSet<rrl_favourite> rrl_favourite { get; set; }
        public virtual DbSet<rrl_fee_config> rrl_fee_config { get; set; }
        public virtual DbSet<rrl_give_personal_money_config> rrl_give_personal_money_config { get; set; }
        public virtual DbSet<rrl_goods> rrl_goods { get; set; }
        public virtual DbSet<rrl_goods_attr> rrl_goods_attr { get; set; }
        public virtual DbSet<rrl_goods_attr_value> rrl_goods_attr_value { get; set; }
        public virtual DbSet<rrl_goods_attr_value_v2> rrl_goods_attr_value_v2 { get; set; }
        public virtual DbSet<rrl_goods_copy> rrl_goods_copy { get; set; }
        public virtual DbSet<rrl_goods_coupons_config> rrl_goods_coupons_config { get; set; }
        public virtual DbSet<rrl_goods_pic> rrl_goods_pic { get; set; }
        public virtual DbSet<rrl_goods_price_record> rrl_goods_price_record { get; set; }
        public virtual DbSet<rrl_goods_recommend> rrl_goods_recommend { get; set; }
        public virtual DbSet<rrl_goods_supplier> rrl_goods_supplier { get; set; }
        public virtual DbSet<rrl_goods_supplier_temp> rrl_goods_supplier_temp { get; set; }
        public virtual DbSet<rrl_order> rrl_order { get; set; }
        public virtual DbSet<rrl_order_info_goods> rrl_order_info_goods { get; set; }
        public virtual DbSet<rrl_page_view_log> rrl_page_view_log { get; set; }
        public virtual DbSet<rrl_platform_data_record> rrl_platform_data_record { get; set; }
        public virtual DbSet<rrl_shop> rrl_shop { get; set; }
        public virtual DbSet<rrl_shop_cart> rrl_shop_cart { get; set; }
        public virtual DbSet<rrl_shop_cate> rrl_shop_cate { get; set; }
        public virtual DbSet<rrl_shop_money_record> rrl_shop_money_record { get; set; }
        public virtual DbSet<rrl_shop_pic> rrl_shop_pic { get; set; }
        public virtual DbSet<rrl_sms> rrl_sms { get; set; }
        public virtual DbSet<rrl_supplier> rrl_supplier { get; set; }
        public virtual DbSet<rrl_trans_body_record> rrl_trans_body_record { get; set; }
        public virtual DbSet<rrl_trans_record> rrl_trans_record { get; set; }
        public virtual DbSet<rrl_type_translate> rrl_type_translate { get; set; }
        public virtual DbSet<rrl_user> rrl_user { get; set; }
        public virtual DbSet<rrl_user_2018_3_11_18_46> rrl_user_2018_3_11_18_46 { get; set; }
        public virtual DbSet<rrl_user_2018_3_11_22_19> rrl_user_2018_3_11_22_19 { get; set; }
        public virtual DbSet<rrl_user_bank_card> rrl_user_bank_card { get; set; }
        public virtual DbSet<rrl_user_money_record> rrl_user_money_record { get; set; }
        public virtual DbSet<rrl_user_money_record_copy> rrl_user_money_record_copy { get; set; }
        public virtual DbSet<rrl_user_plate_to_return_record> rrl_user_plate_to_return_record { get; set; }
        public virtual DbSet<rrl_user_plate_to_return_record_test> rrl_user_plate_to_return_record_test { get; set; }
        public virtual DbSet<rrl_user_receive_info> rrl_user_receive_info { get; set; }
        public virtual DbSet<rrl_user_template> rrl_user_template { get; set; }
        public virtual DbSet<sperader_relation> sperader_relation { get; set; }
        public virtual DbSet<spreader_queue> spreader_queue { get; set; }
        public virtual DbSet<temp> temp { get; set; }
        public virtual DbSet<track_com> track_com { get; set; }
        public virtual DbSet<wx_cache> wx_cache { get; set; }
        public virtual DbSet<area_code> area_code { get; set; }
        public virtual DbSet<bank_main> bank_main { get; set; }
        public virtual DbSet<cash_pool> cash_pool { get; set; }
        public virtual DbSet<roulette_logs> roulette_logs { get; set; }
        public virtual DbSet<rrl_coupons> rrl_coupons { get; set; }
        public virtual DbSet<rrl_goods_coupons> rrl_goods_coupons { get; set; }
        public virtual DbSet<rrl_goods_spec> rrl_goods_spec { get; set; }
        public virtual DbSet<rrl_spreader> rrl_spreader { get; set; }
        public virtual DbSet<rrl_user_play_state> rrl_user_play_state { get; set; }
        public virtual DbSet<CAROUSEL_CHOSEN_LIST_VIEW> CAROUSEL_CHOSEN_LIST_VIEW { get; set; }
        public virtual DbSet<CAROUSEL_MAIN_LIST_VIEW> CAROUSEL_MAIN_LIST_VIEW { get; set; }
        public virtual DbSet<CASH_APPLY_LIST_VIEW> CASH_APPLY_LIST_VIEW { get; set; }
        public virtual DbSet<FAVOURITE_GOODS> FAVOURITE_GOODS { get; set; }
        public virtual DbSet<FAVOURITE_SHOP> FAVOURITE_SHOP { get; set; }
        public virtual DbSet<GOODS_DETAIL_VIEW> GOODS_DETAIL_VIEW { get; set; }
        public virtual DbSet<GOODS_LIST_VIEW> GOODS_LIST_VIEW { get; set; }
        public virtual DbSet<kaquanjilu> kaquanjilu { get; set; }
        public virtual DbSet<ord> ord { get; set; }
        public virtual DbSet<ORDER_COUNT_INFO> ORDER_COUNT_INFO { get; set; }
        public virtual DbSet<ORDER_GOODS_OUT_VIEW> ORDER_GOODS_OUT_VIEW { get; set; }
        public virtual DbSet<ORDER_GOODS_VIEW> ORDER_GOODS_VIEW { get; set; }
        public virtual DbSet<ORDER_LIST_GOODS> ORDER_LIST_GOODS { get; set; }
        public virtual DbSet<ORDER_LIST_VIEW> ORDER_LIST_VIEW { get; set; }
        public virtual DbSet<ORDER_STATUS_COUNT> ORDER_STATUS_COUNT { get; set; }
        public virtual DbSet<orderListView> orderListView { get; set; }
        public virtual DbSet<RECOMMEND_HOT_VIEW> RECOMMEND_HOT_VIEW { get; set; }
        public virtual DbSet<RECOMMEND_MAIN_VIEW> RECOMMEND_MAIN_VIEW { get; set; }
        public virtual DbSet<SHOP_CART_LIST_VIEW> SHOP_CART_LIST_VIEW { get; set; }
        public virtual DbSet<USER_ACCOUNT_VIEW> USER_ACCOUNT_VIEW { get; set; }
        public virtual DbSet<USER_BANK_CARD_VIEW> USER_BANK_CARD_VIEW { get; set; }
        public virtual DbSet<USER_BASE_INFO_VIEW> USER_BASE_INFO_VIEW { get; set; }
        public virtual DbSet<USER_DAY_PLAT_TO_RETURN_VIEW> USER_DAY_PLAT_TO_RETURN_VIEW { get; set; }
        public virtual DbSet<USER_RECEIVE_LIST_VIEW> USER_RECEIVE_LIST_VIEW { get; set; }
        public virtual DbSet<USER_SMS_VALI_VIEW> USER_SMS_VALI_VIEW { get; set; }
        public virtual DbSet<v_gamge_stat_info> v_gamge_stat_info { get; set; }
        public virtual DbSet<v_gamge_stat_info_2018_3_12> v_gamge_stat_info_2018_3_12 { get; set; }
        public virtual DbSet<v_stat_platform_total_info> v_stat_platform_total_info { get; set; }
        public virtual DbSet<v_stat_platform_total_info_2018_3_12> v_stat_platform_total_info_2018_3_12 { get; set; }
        public virtual DbSet<zhuanpanshuju> zhuanpanshuju { get; set; }
    
        public virtual int sp_CART_GOODS_ADD(Nullable<int> uid, Nullable<int> goods_id, Nullable<int> goods_count)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var goods_countParameter = goods_count.HasValue ?
                new ObjectParameter("goods_count", goods_count) :
                new ObjectParameter("goods_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CART_GOODS_ADD", uidParameter, goods_idParameter, goods_countParameter);
        }
    
        public virtual int sp_CART_GOODS_REMOVE(Nullable<int> cart_id, Nullable<int> uid)
        {
            var cart_idParameter = cart_id.HasValue ?
                new ObjectParameter("cart_id", cart_id) :
                new ObjectParameter("cart_id", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CART_GOODS_REMOVE", cart_idParameter, uidParameter);
        }
    
        public virtual int sp_CART_MARK_ITEM_USED(Nullable<int> cart_id)
        {
            var cart_idParameter = cart_id.HasValue ?
                new ObjectParameter("cart_id", cart_id) :
                new ObjectParameter("cart_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CART_MARK_ITEM_USED", cart_idParameter);
        }
    
        public virtual int sp_CASH_APPLY_ADD(Nullable<int> uid, Nullable<byte> type, Nullable<decimal> apply_money, Nullable<int> card_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(byte));
    
            var apply_moneyParameter = apply_money.HasValue ?
                new ObjectParameter("apply_money", apply_money) :
                new ObjectParameter("apply_money", typeof(decimal));
    
            var card_idParameter = card_id.HasValue ?
                new ObjectParameter("card_id", card_id) :
                new ObjectParameter("card_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CASH_APPLY_ADD", uidParameter, typeParameter, apply_moneyParameter, card_idParameter);
        }
    
        public virtual int sp_CLEAN_ALL_ORDER(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CLEAN_ALL_ORDER", lockParameter);
        }
    
        public virtual int sp_EXEC_DAILY_ORDER_CLEAN(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXEC_DAILY_ORDER_CLEAN", lockParameter);
        }
    
        public virtual int sp_EXEC_HISTORY_POINT_TO_MONEY(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXEC_HISTORY_POINT_TO_MONEY", lockParameter);
        }
    
        public virtual int sp_EXEC_ORDER_AUTO_SETTLEMENT(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXEC_ORDER_AUTO_SETTLEMENT", lockParameter);
        }
    
        public virtual int sp_EXEC_PLAT_TO_RETURN(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXEC_PLAT_TO_RETURN", lockParameter);
        }
    
        public virtual int sp_EXEC_REORDER_PAY_BACK(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXEC_REORDER_PAY_BACK", lockParameter);
        }
    
        public virtual int sp_FAOURITE_ADD(Nullable<int> uid, Nullable<int> favourite_id, Nullable<int> favourite_type)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var favourite_idParameter = favourite_id.HasValue ?
                new ObjectParameter("favourite_id", favourite_id) :
                new ObjectParameter("favourite_id", typeof(int));
    
            var favourite_typeParameter = favourite_type.HasValue ?
                new ObjectParameter("favourite_type", favourite_type) :
                new ObjectParameter("favourite_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FAOURITE_ADD", uidParameter, favourite_idParameter, favourite_typeParameter);
        }
    
        public virtual int sp_FAOURITE_REMOVE(Nullable<int> uid, Nullable<int> favourite_id, Nullable<int> favourite_type)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var favourite_idParameter = favourite_id.HasValue ?
                new ObjectParameter("favourite_id", favourite_id) :
                new ObjectParameter("favourite_id", typeof(int));
    
            var favourite_typeParameter = favourite_type.HasValue ?
                new ObjectParameter("favourite_type", favourite_type) :
                new ObjectParameter("favourite_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FAOURITE_REMOVE", uidParameter, favourite_idParameter, favourite_typeParameter);
        }
    
        public virtual int sp_ORDER_ADD_GOODS(Nullable<int> order_id, Nullable<int> goods_id, Nullable<int> goods_count)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var goods_countParameter = goods_count.HasValue ?
                new ObjectParameter("goods_count", goods_count) :
                new ObjectParameter("goods_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_ADD_GOODS", order_idParameter, goods_idParameter, goods_countParameter);
        }
    
        public virtual int sp_ORDER_ADD_NEW(Nullable<int> shop_id, Nullable<int> buyer_id)
        {
            var shop_idParameter = shop_id.HasValue ?
                new ObjectParameter("shop_id", shop_id) :
                new ObjectParameter("shop_id", typeof(int));
    
            var buyer_idParameter = buyer_id.HasValue ?
                new ObjectParameter("buyer_id", buyer_id) :
                new ObjectParameter("buyer_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_ADD_NEW", shop_idParameter, buyer_idParameter);
        }
    
        public virtual int sp_ORDER_CANCEL(Nullable<int> order_id, Nullable<int> uid)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CANCEL", order_idParameter, uidParameter);
        }
    
        public virtual int sp_ORDER_CONFIRM_PAYMENT(Nullable<int> uid, string order_code, Nullable<decimal> money, Nullable<decimal> discount, Nullable<decimal> postage)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_codeParameter = order_code != null ?
                new ObjectParameter("order_code", order_code) :
                new ObjectParameter("order_code", typeof(string));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(decimal));
    
            var postageParameter = postage.HasValue ?
                new ObjectParameter("postage", postage) :
                new ObjectParameter("postage", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CONFIRM_PAYMENT", uidParameter, order_codeParameter, moneyParameter, discountParameter, postageParameter);
        }
    
        public virtual int sp_ORDER_CREATE(Nullable<int> buyer_id, Nullable<int> shop_id, Nullable<int> goods_id, Nullable<int> goods_count)
        {
            var buyer_idParameter = buyer_id.HasValue ?
                new ObjectParameter("buyer_id", buyer_id) :
                new ObjectParameter("buyer_id", typeof(int));
    
            var shop_idParameter = shop_id.HasValue ?
                new ObjectParameter("shop_id", shop_id) :
                new ObjectParameter("shop_id", typeof(int));
    
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var goods_countParameter = goods_count.HasValue ?
                new ObjectParameter("goods_count", goods_count) :
                new ObjectParameter("goods_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CREATE", buyer_idParameter, shop_idParameter, goods_idParameter, goods_countParameter);
        }
    
        public virtual int sp_ORDER_CREATE_BY_CART(Nullable<int> uid, Nullable<int> cart_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var cart_idParameter = cart_id.HasValue ?
                new ObjectParameter("cart_id", cart_id) :
                new ObjectParameter("cart_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CREATE_BY_CART", uidParameter, cart_idParameter);
        }
    
        public virtual int sp_ORDER_CREATE_BY_GOODS(Nullable<int> uid, Nullable<int> goods_id, Nullable<int> goods_count)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var goods_idParameter = goods_id.HasValue ?
                new ObjectParameter("goods_id", goods_id) :
                new ObjectParameter("goods_id", typeof(int));
    
            var goods_countParameter = goods_count.HasValue ?
                new ObjectParameter("goods_count", goods_count) :
                new ObjectParameter("goods_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CREATE_BY_GOODS", uidParameter, goods_idParameter, goods_countParameter);
        }
    
        public virtual int sp_ORDER_CREATE_COMPLETE(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_CREATE_COMPLETE", order_idParameter);
        }
    
        public virtual int sp_ORDER_FILL_RECEIVE_INFO(Nullable<int> uid, Nullable<int> order_id, Nullable<int> receive_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var receive_idParameter = receive_id.HasValue ?
                new ObjectParameter("receive_id", receive_id) :
                new ObjectParameter("receive_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_FILL_RECEIVE_INFO", uidParameter, order_idParameter, receive_idParameter);
        }
    
        public virtual int sp_ORDER_PAY_BACK(Nullable<int> uid, Nullable<int> order_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_PAY_BACK", uidParameter, order_idParameter);
        }
    
        public virtual int sp_ORDER_REFUND(Nullable<int> uid, Nullable<int> order_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_REFUND", uidParameter, order_idParameter);
        }
    
        public virtual int sp_ORDER_REFUND_CLOSE(Nullable<int> uid, Nullable<int> order_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_REFUND_CLOSE", uidParameter, order_idParameter);
        }
    
        public virtual int sp_ORDER_REFUND_NORMAL_RETURN(Nullable<int> uid, Nullable<int> order_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_REFUND_NORMAL_RETURN", uidParameter, order_idParameter);
        }
    
        public virtual int sp_ORDER_SETTLEMENT(Nullable<int> uid, Nullable<int> order_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_SETTLEMENT", uidParameter, order_idParameter);
        }
    
        public virtual int sp_ORDER_TRANS_RECORD_ADD(Nullable<int> buyer_id, string order_code, Nullable<decimal> money, Nullable<decimal> discount_real, Nullable<decimal> postage)
        {
            var buyer_idParameter = buyer_id.HasValue ?
                new ObjectParameter("buyer_id", buyer_id) :
                new ObjectParameter("buyer_id", typeof(int));
    
            var order_codeParameter = order_code != null ?
                new ObjectParameter("order_code", order_code) :
                new ObjectParameter("order_code", typeof(string));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var discount_realParameter = discount_real.HasValue ?
                new ObjectParameter("discount_real", discount_real) :
                new ObjectParameter("discount_real", typeof(decimal));
    
            var postageParameter = postage.HasValue ?
                new ObjectParameter("postage", postage) :
                new ObjectParameter("postage", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ORDER_TRANS_RECORD_ADD", buyer_idParameter, order_codeParameter, moneyParameter, discount_realParameter, postageParameter);
        }
    
        public virtual int sp_PAGE_VIEW_LOG_ADD(string route_info)
        {
            var route_infoParameter = route_info != null ?
                new ObjectParameter("route_info", route_info) :
                new ObjectParameter("route_info", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PAGE_VIEW_LOG_ADD", route_infoParameter);
        }
    
        public virtual int sp_RECEIVE_INFO_ADD(Nullable<int> uid, string name, string address, string mobile, string area_code, string zip_code)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var area_codeParameter = area_code != null ?
                new ObjectParameter("area_code", area_code) :
                new ObjectParameter("area_code", typeof(string));
    
            var zip_codeParameter = zip_code != null ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RECEIVE_INFO_ADD", uidParameter, nameParameter, addressParameter, mobileParameter, area_codeParameter, zip_codeParameter);
        }
    
        public virtual int sp_RECEIVE_INFO_ADD_AS_DEFAULT(Nullable<int> uid, string name, string address, string mobile, string area_code, string zip_code)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var area_codeParameter = area_code != null ?
                new ObjectParameter("area_code", area_code) :
                new ObjectParameter("area_code", typeof(string));
    
            var zip_codeParameter = zip_code != null ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RECEIVE_INFO_ADD_AS_DEFAULT", uidParameter, nameParameter, addressParameter, mobileParameter, area_codeParameter, zip_codeParameter);
        }
    
        public virtual int sp_RECEIVE_INFO_REMOVE(Nullable<int> uid, Nullable<int> receive_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var receive_idParameter = receive_id.HasValue ?
                new ObjectParameter("receive_id", receive_id) :
                new ObjectParameter("receive_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RECEIVE_INFO_REMOVE", uidParameter, receive_idParameter);
        }
    
        public virtual int sp_RECEIVE_INFO_SET_AS_DEFAULT(Nullable<int> uid, Nullable<int> receive_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var receive_idParameter = receive_id.HasValue ?
                new ObjectParameter("receive_id", receive_id) :
                new ObjectParameter("receive_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RECEIVE_INFO_SET_AS_DEFAULT", uidParameter, receive_idParameter);
        }
    
        public virtual int sp_SHOP_ACCOUNT_ADD(Nullable<int> shop_id, Nullable<int> order_id, Nullable<decimal> money, Nullable<decimal> discount_income)
        {
            var shop_idParameter = shop_id.HasValue ?
                new ObjectParameter("shop_id", shop_id) :
                new ObjectParameter("shop_id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var discount_incomeParameter = discount_income.HasValue ?
                new ObjectParameter("discount_income", discount_income) :
                new ObjectParameter("discount_income", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SHOP_ACCOUNT_ADD", shop_idParameter, order_idParameter, moneyParameter, discount_incomeParameter);
        }
    
        public virtual int sp_SMS_ADD(string mobile, string code, Nullable<byte> send_status)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var send_statusParameter = send_status.HasValue ?
                new ObjectParameter("send_status", send_status) :
                new ObjectParameter("send_status", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SMS_ADD", mobileParameter, codeParameter, send_statusParameter);
        }
    
        public virtual int sp_SMS_MARKUSED(Nullable<int> sms_id)
        {
            var sms_idParameter = sms_id.HasValue ?
                new ObjectParameter("sms_id", sms_id) :
                new ObjectParameter("sms_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SMS_MARKUSED", sms_idParameter);
        }
    
        public virtual int sp_test(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_test", order_idParameter);
        }
    
        public virtual int sp_TRANS_BODY_ADD(string order_code, string encrypt_body)
        {
            var order_codeParameter = order_code != null ?
                new ObjectParameter("order_code", order_code) :
                new ObjectParameter("order_code", typeof(string));
    
            var encrypt_bodyParameter = encrypt_body != null ?
                new ObjectParameter("encrypt_body", encrypt_body) :
                new ObjectParameter("encrypt_body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TRANS_BODY_ADD", order_codeParameter, encrypt_bodyParameter);
        }
    
        public virtual int sp_USER_BANK_CARD_ADD(Nullable<int> uid, string bank_en, string card_no, string card_holder)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var bank_enParameter = bank_en != null ?
                new ObjectParameter("bank_en", bank_en) :
                new ObjectParameter("bank_en", typeof(string));
    
            var card_noParameter = card_no != null ?
                new ObjectParameter("card_no", card_no) :
                new ObjectParameter("card_no", typeof(string));
    
            var card_holderParameter = card_holder != null ?
                new ObjectParameter("card_holder", card_holder) :
                new ObjectParameter("card_holder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_BANK_CARD_ADD", uidParameter, bank_enParameter, card_noParameter, card_holderParameter);
        }
    
        public virtual int sp_USER_BANKCARD_REMOVE(Nullable<int> uid, Nullable<int> card_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var card_idParameter = card_id.HasValue ?
                new ObjectParameter("card_id", card_id) :
                new ObjectParameter("card_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_BANKCARD_REMOVE", uidParameter, card_idParameter);
        }
    
        public virtual int sp_USER_MONEY_RECORD_ADD(Nullable<int> uid, Nullable<int> order_id, Nullable<decimal> money, Nullable<int> type, string remark)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_MONEY_RECORD_ADD", uidParameter, order_idParameter, moneyParameter, typeParameter, remarkParameter);
        }
    
        public virtual int sp_USER_PLATE_TO_RETURN_ADD(Nullable<int> uid, Nullable<int> order_id, Nullable<decimal> plat_to_return_add)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var plat_to_return_addParameter = plat_to_return_add.HasValue ?
                new ObjectParameter("plat_to_return_add", plat_to_return_add) :
                new ObjectParameter("plat_to_return_add", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_PLATE_TO_RETURN_ADD", uidParameter, order_idParameter, plat_to_return_addParameter);
        }
    
        public virtual int sp_USER_PLATE_TO_RETURN_RECORD_ADD(Nullable<int> uid, Nullable<int> order_id, Nullable<decimal> money, Nullable<int> type, string remark)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_PLATE_TO_RETURN_RECORD_ADD", uidParameter, order_idParameter, moneyParameter, typeParameter, remarkParameter);
        }
    
        public virtual int sp_USER_RECOMMEND_AWARD(Nullable<int> uid, Nullable<int> order_id, Nullable<decimal> award_money)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var award_moneyParameter = award_money.HasValue ?
                new ObjectParameter("award_money", award_money) :
                new ObjectParameter("award_money", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_RECOMMEND_AWARD", uidParameter, order_idParameter, award_moneyParameter);
        }
    
        public virtual int sp_USER_REGIST(string username, string spreader)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var spreaderParameter = spreader != null ?
                new ObjectParameter("spreader", spreader) :
                new ObjectParameter("spreader", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_REGIST", usernameParameter, spreaderParameter);
        }
    
        public virtual int sp_USER_REGIST_AWARD(Nullable<int> spreader_uid, string username)
        {
            var spreader_uidParameter = spreader_uid.HasValue ?
                new ObjectParameter("spreader_uid", spreader_uid) :
                new ObjectParameter("spreader_uid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_REGIST_AWARD", spreader_uidParameter, usernameParameter);
        }
    
        public virtual int sp_USER_SET_BASE_INFO(Nullable<int> uid, string nick_name, Nullable<byte> sex, string area_code)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var nick_nameParameter = nick_name != null ?
                new ObjectParameter("nick_name", nick_name) :
                new ObjectParameter("nick_name", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(byte));
    
            var area_codeParameter = area_code != null ?
                new ObjectParameter("area_code", area_code) :
                new ObjectParameter("area_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_SET_BASE_INFO", uidParameter, nick_nameParameter, sexParameter, area_codeParameter);
        }
    
        public virtual int sp_USER_SET_HEAD_PIC(Nullable<int> uid, Nullable<int> pic_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var pic_idParameter = pic_id.HasValue ?
                new ObjectParameter("pic_id", pic_id) :
                new ObjectParameter("pic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_USER_SET_HEAD_PIC", uidParameter, pic_idParameter);
        }
    
        public virtual int sp_EVENT_VIEW_COUNT_ADD(string route_info)
        {
            var route_infoParameter = route_info != null ?
                new ObjectParameter("route_info", route_info) :
                new ObjectParameter("route_info", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EVENT_VIEW_COUNT_ADD", route_infoParameter);
        }
    
        public virtual int sp_EXE_REORDER_PAY_BACK(Nullable<int> @lock)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EXE_REORDER_PAY_BACK", lockParameter);
        }
    
        public virtual int sp_platform_add_data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_platform_add_data");
        }
    
        public virtual int sp_REFRESH_RELATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_REFRESH_RELATION");
        }
    
        public virtual int sp_TICKET_AREA_PAY_BACK(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TICKET_AREA_PAY_BACK", order_idParameter);
        }
    
        public virtual int sp_v3_confirm_order_task(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_v3_confirm_order_task", order_idParameter);
        }
    }
}
