//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP_CART_LIST_VIEW
    {
        public int id { get; set; }
        public int uid { get; set; }
        public int goods_id { get; set; }
        public int goods_count { get; set; }
        public int shop_id { get; set; }
        public string shop_name { get; set; }
        public string goods_name { get; set; }
        public string propaganda { get; set; }
        public string specification { get; set; }
        public decimal price { get; set; }
        public long pic_id { get; set; }
        public decimal postage { get; set; }
        public Nullable<int> limit { get; set; }
    }
}
