//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_BASE_INFO_VIEW
    {
        public int uid { get; set; }
        public string username { get; set; }
        public string nick_name { get; set; }
        public byte sex { get; set; }
        public string area_code { get; set; }
        public string head_pic { get; set; }
    }
}
