//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_gamge_stat_info_2018_3_12
    {
        public string StatisticalDate { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> UserMoney { get; set; }
        public int no_received_free_count { get; set; }
        public decimal no_received_free_money { get; set; }
        public int no_received_pay_count { get; set; }
        public decimal no_received_pay_money { get; set; }
        public int received_free_count { get; set; }
        public decimal received_free_money { get; set; }
        public int received_pay_count { get; set; }
        public decimal received_pay_money { get; set; }
        public Nullable<int> all_playtimes { get; set; }
        public Nullable<decimal> all_winlose_money { get; set; }
        public int game0001_playtimes { get; set; }
        public decimal game0001_winlose_money { get; set; }
        public Nullable<int> game0002_playtimes { get; set; }
        public Nullable<decimal> game0002_winlose_money { get; set; }
        public Nullable<int> game0003_playtimes { get; set; }
        public Nullable<decimal> game0003_winlose_money { get; set; }
        public Nullable<int> game0004_playtimes { get; set; }
        public Nullable<decimal> game0004_winlose_money { get; set; }
        public Nullable<int> game0005_playtimes { get; set; }
        public Nullable<decimal> game0005_winlose_money { get; set; }
        public int BuyBeanCount { get; set; }
        public decimal BuyBeanMoney { get; set; }
        public int PayMoneyCount { get; set; }
        public decimal PayMoneyMoney { get; set; }
        public int UseBeanOrderCount { get; set; }
        public decimal UseBeanOrderMoney { get; set; }
    }
}
