//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_stat_platform_total_info_2018_3_12
    {
        public string 时间 { get; set; }
        public decimal 用户剩余金豆总额 { get; set; }
        public int 购买小红包次数 { get; set; }
        public decimal 购买小红包金额 { get; set; }
        public int 分享红包领取次数 { get; set; }
        public decimal 分享红包领取金额 { get; set; }
        public int 分时段红包次数 { get; set; }
        public decimal 分时段红包金额 { get; set; }
        public Nullable<int> 每日红包领取次数 { get; set; }
        public Nullable<decimal> 每日红包领取金额 { get; set; }
        public int 首次进入游戏次数 { get; set; }
        public decimal 首次进入游戏总赠送金豆数 { get; set; }
        public int 购买金豆交易次数 { get; set; }
        public int 购买金豆人数 { get; set; }
        public decimal 当日购入金豆总数 { get; set; }
        public Nullable<int> 游戏总出资次数 { get; set; }
        public Nullable<decimal> 游戏总出资金额 { get; set; }
        public Nullable<int> 游戏总获胜次数 { get; set; }
        public Nullable<decimal> 游戏奖励金豆总数 { get; set; }
        public Nullable<int> 参与游戏总人数 { get; set; }
        public int 当日使用金豆购物次数 { get; set; }
        public decimal 当日使用金豆购物金额 { get; set; }
        public int 当日使用现金购物次数 { get; set; }
        public decimal 当日使用现金购物金额 { get; set; }
    }
}
