//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_cache
    {
        public int id { get; set; }
        public string access_token { get; set; }
        public System.DateTime access_token_timestamp { get; set; }
        public int access_token_expire { get; set; }
        public string jsapi_ticket { get; set; }
        public System.DateTime jsapi_ticket_timestamp { get; set; }
        public int jsapi_ticket_exppire { get; set; }
    }
}
