//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhuanpanshuju
    {
        public string 时间 { get; set; }
        public int 分享红包领取次数 { get; set; }
        public decimal 分享总赠送金豆数 { get; set; }
        public int 每日红包领取次数 { get; set; }
        public decimal 每日红包总赠送金豆数 { get; set; }
        public int 首次进入游戏次数 { get; set; }
        public decimal 首次进入游戏总赠送金豆数 { get; set; }
        public int 购买金豆交易次数 { get; set; }
        public decimal 当日购入金豆总数 { get; set; }
        public int 游戏获胜次数 { get; set; }
        public decimal 游戏奖励金豆总数 { get; set; }
        public int 当日出资次数 { get; set; }
        public decimal 当日出资总额 { get; set; }
        public int 当日参与游戏人数 { get; set; }
        public int 当日使用金豆购物人数 { get; set; }
    }
}
